// Built-in content engine: word banks + generators used when no LLM key is set (or the LLM is
// slow/rejected). Each generator takes a context `c` ({vars, players, mem, rng}) and returns a string.
// When ANTHROPIC_API_KEY is present the same slots are generated by the model instead.

export const pick = (arr, rng = Math.random) => arr[Math.floor(rng() * arr.length)];
export const shuffle = (arr, rng = Math.random) => {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

export const POOLS = {
  creatures: ['a whale', 'a moth the size of a bus', 'a polite crow', 'a sentient lasagna', 'a heron in a raincoat', 'a three-legged goat', 'a jellyfish with opinions', 'a lighthouse that walks', 'a very old pigeon', 'a hundred tiny lobsters'],
  objects: ['a toilet', 'a grand piano', 'a damp sock', 'a traffic cone', 'a chandelier', 'a rotary phone', 'a bowl of soup', 'a tuba', 'a vending machine', 'a single enormous eyebrow'],
  places: ['Mars', 'the inside of a cloud', 'a flooded mall', 'the back of the moon', 'a parking garage at the end of time', 'Neptune\'s waiting room', 'a sofa dimension', 'the bottom of a pocket', 'a haunted spa', 'Tuesday'],
  suns: ['a damp sock', 'a lukewarm waffle', 'a tuba', 'a very large grape', 'a disappointed lamp', 'a single glowing eyebrow', 'a rotating hot dog', 'a big sad moth'],
  dreamA: ['WHALE', 'MOTH', 'HERON', 'LASAGNA', 'LIGHTHOUSE', 'JELLYFISH', 'GOAT', 'PIGEON'],
  dreamB: ['TOILET', 'PIANO', 'SOCK', 'CHANDELIER', 'TUBA', 'VENDING MACHINE', 'SOUP', 'EYEBROW'],
  dreamC: ['MARS', 'THE INSIDE OF A CLOUD', 'A FLOODED MALL', 'THE BACK OF THE MOON', 'TUESDAY', 'A SOFA DIMENSION', 'A HAUNTED SPA', 'NEPTUNE'],
  doors: ['OPEN IT', 'DO NOT OPEN IT', 'KNOCK TWICE', 'LICK THE HANDLE (IMAGINARY)'],
  directions: ['toward the humming', 'toward the warm smell', 'directly into the wall', 'sideways, forever', 'toward the large soft sound'],
  predictions: ['the lights flicker', 'someone says "wait, what?"', 'a phone buzzes that is not this one', 'a snack is mentioned', 'someone stands up for no reason', 'a long silence'],
  tribute: ['a left shoe', 'a half-finished sentence', 'a memory of Tuesday', 'the good pen', 'a perfectly average hat'],
  ticks: ['the warm hum', 'the second moon', 'the lukewarm wind', 'the faint smell of toast'],
};

export const SECRET_MISSIONS = [
  'Without explaining, get someone to look at the ceiling.',
  'Say the word "banana" in a completely normal sentence.',
  'Get two people to stand up at the same time.',
  'Make someone hold out their hand, palm up, for no stated reason.',
  'Whisper "it is happening" to someone and then act like you said nothing.',
  'Quietly start humming the same note. See who joins.',
  'Ask a person what time it is on Neptune. Remain serious.',
  'Get someone to say the word "moist" out loud.',
  'Slowly move your chair half a meter to the left without comment.',
  'Point at something innocent in the room and nod knowingly.',
  'Get a person to swap seats with someone.',
  'Introduce yourself to someone you know, as if for the first time.',
  'Start narrating your own movements in a hushed documentary voice.',
  'Compliment an object in the room with real sincerity.',
  'Tell someone you can feel the weather changing. It is indoors.',
  'Get everyone to say "hmm" at the same time.',
];

export const IDENTITY_MISSIONS = [
  'Subtly act like {other} for the next minute. Do not say who you are being.',
];

export const FLOORS = ['warm pudding', 'a thin layer of static', 'the surface of a drum', 'sleeping cats', 'cold soup', 'an aggressive carpet', 'a polite lake'];

const SPECIES = ['Homo Snackus', 'the Damp Philosopher', 'Gloopus Maximus', 'a Bureaucratic Moth', 'the Soft Menace', 'Corridor Walker', 'the Anxious Comet', 'Homo Couchus', 'Sock Goblin (Apex)', 'the Reluctant Prophet'];
const CRIMES = ['stealing the moon and returning a slightly smaller one', 'unauthorized tampering with Tuesday', 'impersonating a lighthouse', 'holding a grudge against a cloud', 'laundering several small thoughts', 'the unlicensed summoning of a pigeon', 'borrowing a sunset without asking', 'knowingly existing near a vending machine', 'conspiracy to make a spoon act suspicious', 'sneaking a whole ocean into a bag'];
const EVIDENCE = ['A blurry photo of a shadow that looks exactly like guilt.', 'Exhibit A: a receipt for one (1) moon.', 'A witness, who was a sock, says it "saw everything and understood nothing".', 'Fingerprints found on a cloud. Cloud declined comment.', 'A suspicious smell of toast at the scene.', 'Security footage shows the accused moving "in a way".', 'A single feather. Nobody can explain the feather.', 'The accused was seen humming at 3:14 PM. Nobody hums at 3:14 PM.'];
const SENTENCES = ['Must refer to the nearest lamp as "Sir" for ten minutes.', 'Sentenced to deliver one extremely dramatic sigh whenever anyone says "okay".', 'Must now speak only in weather reports until the next anomaly.', 'Banished to the other end of the couch, with honors.', 'Must greet the next three people who enter with a small bow.', 'Shall be known as "The Moon Thief" until further notice.', 'Must pronounce every word slightly wrong for five minutes.', 'Sentenced to hold an imaginary orchestra baton whenever the room goes quiet.'];
const RITUALS = ['the Ceremony of the Unfinished Snack', 'a forty-step apology to a houseplant', 'the Great Rearranging of Things Nobody Needs', 'a lullaby for a malfunctioning toaster', 'the Annual Counting of the Ceiling Dots', 'a quiet war with a sleeve'];
const MISSING = ['the color between blue and Thursday', 'all but one of the sounds that start with "b"', 'the concept of pockets', 'the left side of the room (temporarily)', 'the feeling of having just entered a room', 'about eleven percent of the carpet'];
const COSMIC_FIRST = ['Lord', 'Dame', 'Captain', 'Archduke', 'Professor', 'Saint', 'Grand', 'Wing Commander'];
const COSMIC_MID = ['Dampwhisker', 'Gravel', 'Moth', 'Nimbus', 'Crumb', 'Hexagon', 'Pudding', 'Static', 'Eclipse', 'Murmur'];
const COSMIC_LAST = ['of the Hallway', 'the Mildly Radiant', 'Third of Their Name', 'the Slightly Forgotten', 'of Unclear Orbit', 'the Soft-Spoken', 'Who Hums'];
const READOUT_PARTS = ['raccoon', 'unpaid parking ticket', 'thundercloud', 'tax form', 'houseplant', 'unresolved argument', 'kettle', 'moth', 'mid-sized cathedral', 'rumor', 'lukewarm bath', 'wizard (retired)'];
const QUESTIONS = ['When did you last blink without permission?', 'How many of your thoughts are borrowed?', 'Describe the color of your Tuesday in one hum.', 'Which of your knees do you trust?', 'What does the inside of your sleeve know about you?', 'At what temperature do you become dishonest?', 'If your shadow left, what would it say about you?', 'Have you recently apologized to furniture?'];
const BEHIND_DOOR = ['A very small room containing a very large sigh.', 'An empty corridor that is slightly proud of itself.', 'Twelve identical geese looking away in unison.', 'A second door. Slightly better.', 'A closet of old weather. It is mostly drizzle.', 'Your own Tuesday, wearing a coat.'];
const DREAM_LINES = ['Warm light spills from something that is definitely not a window.', 'The ground hums, reluctantly, in B flat.', 'Somewhere a door is learning to open itself.', 'The sky is made of slow paperwork.', 'You feel followed by a very polite shadow.'];
const JOIN = ['shall', 'must', 'will', 'cannot', 'secretly'];
const FIELD = [
  'Observation log: {quiet} has spoken the least. I assume a plan. Or a snack.',
  'Observation log: the group agrees on nothing, yet sits closer together every minute. Illogical. Beautiful.',
  'Observation log: {top} is chosen often. I do not know why. Neither does {top}.',
  'Observation log: {n} events have occurred. Not one of you looked away fast enough.',
];

export const FALLBACKS = {
  crime: () => pick(CRIMES),
  evidence: () => pick(EVIDENCE),
  sentence: () => pick(SENTENCES),
  species: () => pick(SPECIES),
  ritual: () => pick(RITUALS),
  missing_thing: () => pick(MISSING),
  floor_material: () => pick(FLOORS),
  alien_question: () => pick(QUESTIONS),
  door_result: () => pick(BEHIND_DOOR),
  dream_line: () => pick(DREAM_LINES),
  cosmic_name: () => `${pick(COSMIC_FIRST)} ${pick(COSMIC_MID)} ${pick(COSMIC_LAST)}`,
  readout: (c) => {
    const parts = shuffle(READOUT_PARTS, c.rng).slice(0, 3);
    const a = 40 + Math.floor(c.rng() * 40), b = Math.floor(c.rng() * (100 - a - 5)), d = 100 - a - b;
    return `${a}% ${parts[0]}, ${b}% ${parts[1]}, ${d}% ${parts[2]}.`;
  },
  creature: (c) => {
    const bits = shuffle(['Moth', 'Lantern', 'Gloop', 'Beak', 'Sock', 'Orb', 'Choir', 'Tooth', 'Hum', 'Noodle', 'Cloud', 'Drum'], c.rng);
    return `The ${bits[0]}-${bits[1]} (${pick(['feeds on small silences', 'is afraid of exactly one chair', 'hums in the key of Wednesday', 'has four opinions and no mouth', 'is mostly eyelashes', 'weighs less than a rumor'])})`;
  },
  mistranslation: (c) => {
    const t = (c.vars.last_text || 'something').slice(0, 60);
    return `Mistranslated from Human: "${t}" is a sacred rite of ${pick(RITUALS)}.`;
  },
  word_prophecy: (c) => {
    const w = (c.vars.words || []).filter(Boolean);
    if (w.length < 2) return 'The words said nothing. Which is also prophecy.';
    const s = shuffle(w, c.rng);
    return `It is written: the ${s[0]} ${pick(JOIN)} ${s[1] ? 'consume' : 'wait'} the ${s[1] || 'void'}${s[2] ? `, and the ${s[2]} will not be consulted` : ''}.`;
  },
  field_report: (c) => {
    const m = c.mem;
    const quiet = m?.quietest || pick(c.players, c.rng) || 'someone';
    const top = m?.mostChosen || pick(c.players, c.rng) || 'someone';
    return pick(FIELD, c.rng).replaceAll('{quiet}', quiet).replaceAll('{top}', top).replaceAll('{n}', String(m?.eventCount ?? 0));
  },
  conclusion: (c) => {
    const who = c.vars.leader || 'one of you';
    return `${who} has been classified as ${pick(SPECIES)}. The others are merely suspicious.`;
  },
  law: () => pick(['Must refer to the nearest lamp as "Sir".', 'Must sigh whenever someone says "okay".', 'Must announce each sip of any beverage like weather.', 'Must greet the next object they touch.']),
  free: () => 'Something has happened.',
};

/** Slot -> instruction for the LLM (kept short; persona voice + safety are added by the host). */
export const SLOT_BRIEFS = {
  crime: 'One absurd, harmless "crime" a cosmic court might charge someone with. Under 14 words. No real-world crime, no violence.',
  evidence: 'One piece of ridiculous evidence presented at a cosmic trial. Under 22 words. Harmless and surreal.',
  sentence: 'A ridiculous, harmless, physically safe sentence for a player to obey for a few minutes. Under 22 words.',
  species: 'A funny made-up species or classification for a human. Under 6 words.',
  ritual: 'A bizarre ritual or ceremony. Under 12 words.',
  missing_thing: 'Something abstract or absurd that went missing from reality. Under 12 words.',
  floor_material: 'A strange material or substance the floor has become. Under 6 words.',
  alien_question: 'A bizarre, unanswerable-sounding question an alien interrogator asks a human. Under 16 words. Must NOT be a classic icebreaker.',
  door_result: 'What was behind a mysterious door. One surprising, surreal sentence. Under 22 words.',
  dream_line: 'One line narrating a surreal dreamlike location. Under 20 words.',
  cosmic_name: 'A grand, silly cosmic title/name for a human, e.g. "Lord Dampwhisker of the Hallway". Under 7 words.',
  readout: 'A scanner readout for one person as percentages of absurd things summing to 100%. One line, e.g. "61% raccoon, 22% tax form, 17% unresolved argument."',
  creature: 'A newly-summoned absurd creature: a name and a short parenthetical oddity. Under 18 words.',
  mistranslation: 'Take the human sentence in {last_text} and "mistranslate" it into an alien reading of a grand ritual. One or two sentences.',
  word_prophecy: 'A one-sentence prophecy that must use ALL of these words: {words}. Cryptic and funny.',
  field_report: 'A short observation-log entry about this group using the session memory provided. Under 28 words. Reference real patterns (who is quiet, who is chosen often).',
  conclusion: 'A funny pseudo-scientific conclusion about {leader}, who was just picked by the group. Under 24 words.',
  law: 'A harmless, physically safe, slightly absurd law one player must follow for ten minutes. Under 16 words.',
};
